version: "3.9"

services:
  db:
    image: postgres:15
    container_name: cricketstore_db
    restart: always
    environment:
      POSTGRES_DB: cricketstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: cricketstore_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always

  web:
    build: .
    container_name: cricketstore_web
    command: gunicorn cricketstore.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
      - elasticsearch
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: cricketstore.settings
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  es_data:
